### PR TITLE
Tilemap and Collider Integration

### PR DESCRIPTION
**Pull request by Belize22**
- Colliders are now auto-generated when drawing tiles (multiple layers to differentiate between floors, metal walls, and earth walls.
- This implementation does not support corner tiles that is of earth material. It has been concluded that relegating earth walls to non-corner tiles is more efficient in the long-term than supporting it (since the implementation of doing so yield a cost benefit ratio that is too high).
- Renamed scene1 into TestLevel. Deleted some irrelevant scenes.

### CODE REVIEW

**Review by Megan-VanHumbeck — APPROVED** [review]
It looks good but there seems to be something odd about the PR. It seems to be comparing to an older version of Dev. Maybe pulling dev into the branch again will fix it?

**Comment by Belize22** [comment]
Merged dev into this branch again to update it once again. If it still seems outdated, maybe it is because this branch is kinda old (David experimented with the tilemap colliders before I pieced everything together).

**Comment by Megan-VanHumbeck** [comment]
> 
> 
> Merged dev into this branch again to update it once again. If it still seems outdated, maybe it is because this branch is kinda old (David experimented with the tilemap colliders before I pieced everything together).

That fixed the problem, thanks!

**Review by DavidoBod — APPROVED** [review]
good stuff

**Pull request merged**
